# application.yml

h2:
    console:
        enabled: true

cloud:
    config:
        enabled: true
    discovery:
        enabled: true
config:
    import: optional:configserver:http://localhost:9999

eureka:
    client:
        service-url:
            defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/}

    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
global:
    params:
        p1: 9999
        p2: 8888
