# application.yml

eureka:
    client:
        service-url:
            defaultZone: http://eureka-service:8761/eureka/
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
