# application.yml

server:
    port: 8080

# Configuration pour la découverte des services avec Eureka
eureka:
    client:
        service-url:
            defaultZone: http://eureka-service:8761/eureka/
    instance:
        prefer-ip-address: true

# Configuration des routes pour Spring Cloud Gateway
spring:
    cloud:
        gateway:
            routes:
                -   id: library-service
                    uri: lb://library-service  # Utilisation d'un équilibreur de charge pour le service library
                    predicates:
                        - Path=/library/**  # Routage basé sur le chemin /library/**
                -   id: user-service
                    uri: lb://user-service  # Utilisation d'un équilibreur de charge pour le service user
                    predicates:
                        - Path=/users/**  # Routage basé sur le chemin /users/**
                -   id: loan-service
                    uri: lb://loan-service  # Utilisation d'un équilibreur de charge pour le service loan
                    predicates:
                        - Path=/loans/**  # Routage basé sur le chemin /loans/**
                -   id: notification-service
                    uri: lb://notification-service  # Utilisation d'un équilibreur de charge pour le service notification
                    predicates:
                        - Path=/notifications/**  # Routage basé sur le chemin /notifications/**
